image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  CI_REGISTRY_IMAGE: kdt-gitlab.elice.io/sw_track/class_04/web_2_project/team10/dev-be
  TAG: dev

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "matissue" -p "ubinzzang" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker-compose up -d
