services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  CI_REGISTRY: kdt-gitlab.elice.io:5050
  CI_REGISTRY_IMAGE: kdt-gitlab.elice.io/sw_track/class_04/web_2_project/team10/dev-be
  TAG: dev

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - set -e
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG

deploy:
  stage: deploy
  only:
    - dev
  script:
    - set -e
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker-compose up -d
